linear_reference_genome:      # for pangenie and locityper
  label: hg38ref
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/hg38.no_alt.fa.gz      # plain .fasta also works

pangenome_reference_graph:    # for pangenie and locityper
  label: graphref
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/cactus_filtered_ids.vcf.gz      # plain .vcf also works

reference_callset:            # for pangenie only
  label: callsetref
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/cactus_filtered_ids_biallelic.vcf.gz

loci_catalog:                 # for locityper only
  label: lociset
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/loci.bed

cram_reference_genome:        # for locityper only
  label: grch38decoyhla 
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/GRCh38_full_analysis_set_plus_decoy_hla.fa.gz

tools: "pangenie,locityper"           # or set via --config tools=... on the CLI instead