
# Reference files for PanGenie and locityper
# See the PanGenie documentation/wiki for more details:
# https://github.com/eblerjana/pangenie/wiki/D:-Running-PanGenie-on-HPRC-data

# The linear reference genome (pangenie, locityper) such as hg38 or chm13/T2T
# is expected to be in fasta format, and may optionally be gzipped.
# Valid example input file:
# https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/HGSVC2/technical/reference/20200513_hg38_NoALT/hg38.no_alt.fa.gz
linear_reference_genome:
  label: hg38
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/hg38.no_alt.fa.gz
  
# The pangenome reference graph (pangenie, locityper) is expected to be a variation graph in vcf format,
# and may optionally be gzipped.
# Valid example input files:
# https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/scratch/2025_02_28_minigraph_cactus/hprc-v2.0-mc-grch38/hprc-v2.0-mc-grch38.pgin.vcf.gz
# https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=pangenomes/scratch/2025_12_23_minigraph_cactus/hprc-v2.1-mc-grch38/hprc-v2.1-mc-grch38.vcf.gz
pangenome_reference_graph:
  label: hprc21grch38graph
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/hprc-v2.1-mc-grch38.vcf.gz

# The reference callset  (pangenie)is expected to be in vcf format, and may optionally be gzipped.
# Valid example input files:
# https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/scratch/2025_02_28_minigraph_cactus/hprc-v2.0-mc-grch38/hprc-v2.0-mc-grch38.pgbi.vcf.gz
# https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=pangenomes/scratch/2025_12_23_minigraph_cactus/hprc-v2.1-mc-grch38/hprc-v2.1-mc-grch38.wave.vcf.gz
reference_callset:
  label: hprc21grch38callset
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/hprc-v2.1-mc-grch38.wave.vcf.gz

# The loci catalog  (locityper)is expected to be in bed format. Tab separated, with 3 columns: 
# chrom, start, end, optional name.
# Valid example input file can be found here:
# https://zenodo.org/records/11068261
loci_catalog:
  label: clientlociset
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/2026-07-20-MODY_gene-list.bed
  
# The CRAM reference genome (locityper) is expected to be in fasta format, and may optionally be gzipped.
# Valid example input file:
# https://42basepairs.com/browse/s3/1000genomes/technical/reference/GRCh38_reference_genome?file=GRCh38_full_analysis_set_plus_decoy_hla.fa
cram_reference_genome:        # for locityper only
  label: grch38decoyhla 
  path: /gpfs/project/projects/medbioinf/projects/cubi/projects/nextgen-genotyping/wd/input_data/GRCh38_full_analysis_set_plus_decoy_hla.fa.gz


# Specify which tools to run in the pipeline. Options are: pangenie, locityper
# This can also be set via --config tools=... on the CLI instead
tools: "pangenie,locityper"


# Config options to use reference container
# as part of the pipeline
use_reference_container: false
# If use_reference_container is set to true, the following
# two options must be specified as well in the config

# Existing path to directory with reference container (*.sif) files.
# This option is specific to the execution infrastructure.
# reference_container_store: <PATH>

# List of container names to be used in the pipeline
# reference_container_names:
#   - name1
#   - name2
